### ISSUE TITLE
POC2 Filename support

### ISSUE THREAD

**Issue by JohnnyFFM** [guneyozsan/burst-corrupted-plot-detector#1]
Hey!
I love your tool! Very efficient to track down borked plot files. Would be cool if you could patch it to support POC2 filename. I think its a quick fix, just modify plot_file::suits_file_name_format to also accept files with 2 separators. 

Many thanks, 

Johnny

**Comment by guneyozsan** [comment]
Hi Johnny!

Thanks for the notice and the hint. I released a new version that adds POC2 file name support:
https://github.com/guneyozsan/burst-corrupted-plot-detector/releases/tag/v1.2.0

Because of a new addition to our family I couldn't update my Burst plots yet. That would be awesome if you could test it with some logs generated from POC2 files and let me know how it goes. The fix was pretty straightforward but, you know, in case:)

**Comment by JohnnyFFM** [comment]
Thanks will test!

**Comment by JohnnyFFM** [comment]
And tested! Works well! Thanks for the quick fix!

**Comment by guneyozsan** [comment]
You're welcome. Thanks for the hand.
